In [75]:
import pandas as pd
import sklearn
import numpy as np
from sklearn.model_selection import KFold,cross_val_score
from sklearn.linear_model import LinearRegression

In [76]:
data=pd.read_csv('kc_house_data.csv')

In [77]:
data.head()

id             date     price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900.0         3       1.00         1180   
1  6414100192  20141209T000000  538000.0         3       2.25         2570   
2  5631500400  20150225T000000  180000.0         2       1.00          770   
3  2487200875  20141209T000000  604000.0         4       3.00         1960   
4  1954400510  20150218T000000  510000.0         3       2.00         1680   

   sqft_lot  floors  waterfront  view     ...      grade  sqft_above  \
0      5650     1.0           0     0     ...          7      1180.0   
1      7242     2.0           0     0     ...          7      2170.0   
2     10000     1.0           0     0     ...          6       770.0   
3      5000     1.0           0     0     ...          7      1050.0   
4      8080     1.0           0     0     ...          8      1680.0   

   sqft_basement  yr_built  yr_renovated  zipcode      lat     long  \
0              0      1955             0    98178  47.5112 -122.257   
1            400      1951          1991    98125  47.7210 -122.319   
2              0      1933             0    98028  47.7379 -122.233   
3            910      1965             0    98136  47.5208 -122.393   
4              0      1987             0    98074  47.6168 -122.045   

   sqft_living15  sqft_lot15  
0           1340        5650  
1           1690        7639  
2           2720        8062  
3           1360        5000  
4           1800        7503  

[5 rows x 21 columns]

In [78]:
type(data)

pandas.core.frame.DataFrame

In [79]:
y=(np.array(data['price'],dtype='float64').reshape(-1,1) )

In [80]:
y.shape

(21613, 1)

In [106]:

X=data.drop('date',axis=1)

In [107]:
X=X.dropna(axis=0)
X.isna().sum()

id               0
price            0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
grade            0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
zipcode          0
lat              0
long             0
sqft_living15    0
sqft_lot15       0
dtype: int64

In [108]:
X=np.array(X)

In [109]:
kf=KFold(n_splits=2)#can increase the spliot as we wis\h


In [110]:
k=list(kf.split(X))

In [111]:
i=1
for train,test in k:
    print('\ntrain'+str(i),train)
    print('Test'+str(i),test)
    i=i+1


train1 [10806 10807 10808 ... 21608 21609 21610]
Test1 [    0     1     2 ... 10803 10804 10805]

train2 [    0     1     2 ... 10803 10804 10805]
Test2 [10806 10807 10808 ... 21608 21609 21610]


In [112]:
k

[(array([10806, 10807, 10808, ..., 21608, 21609, 21610]),
  array([    0,     1,     2, ..., 10803, 10804, 10805])),
 (array([    0,     1,     2, ..., 10803, 10804, 10805]),
  array([10806, 10807, 10808, ..., 21608, 21609, 21610]))]

In [113]:
len(train),len(test)

(10806, 10805)

In [114]:
x_train1,y_train1=X[k[0][0]],y[k[0][0]]
x_test1,y_test1=X[k[0][1]],y[k[0][1]]
x_train2,y_train2=X[k[1][0]],y[k[1][0]]
x_test2,y_test2=X[k[1][1]],y[k[1][1]]

In [115]:
y_test1.shape

(10806, 1)

In [116]:
reg=LinearRegression()
reg1=LinearRegression()

In [117]:
reg.fit(x_train2,y_train2)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [118]:
reg1.fit(x_train1,y_train1)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [119]:
reg.score(x_test1,y_test1)

0.0017187434168769446

In [120]:
reg1.score(x_test2,y_test2)

0.003450557462729265

In [122]:
cross_val_score(reg,X,y,cv=2)

ValueError: Found input variables with inconsistent numbers of samples: [21611, 21613]